### ISSUE TITLE
Question: How to use MarkyMark in Swift 3

### ISSUE THREAD

**Issue by NallapatiMalleswari** [M2Mobi/Marky-Mark#33]

**Comment by jvanzummeren** [comment]
Can you provide more information on what this issue is about?

**Comment by NallapatiMalleswari** [comment]
Hi,
It is an issue with swift3.it's not working in swift3

**Comment by jvanzummeren** [comment]
MarkyMark has a different main version for each version of Swift. The newest version is for Swift 4.
In order to use MarkyMark in Swift 3, please specify a version in your Podfile like so:

`    pod 'markymark', '~> 3.0`

For more information about versions of Markymark, please check out this page:
https://github.com/M2Mobi/Marky-Mark/releases

If you have any more issues, feel free to post another issue.

**Comment by NallapatiMalleswari** [comment]
thankyou
